package lk.kolitha.dana.enums;

public enum CharityProofDocumentType {
    ID_CARD, PASSPORT, DRIVING_LICENCE,BUSINESS_REGISTRATION_CERTIFICATE, REQUEST_FOR_PROOF_OF_ADDRESS,
    REQUEST_LETTER_OF_REFERRAL, OTHERS
}
